name = "tf-cf-dni-mgmt"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
name = "tf-cf-dni-mgmt"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "tf-cf-dni-mgmt-staging"
vars = { ENVIRONMENT = "staging" }
